#!/usr/bin/env python3
# in theory 99% of the time spent in IO wait so it doesn't matter that python is a slow language?
# edit: it does matter. this is twice as slow as `du`.
import os
import sys
import pwd
import time

# import signal
# import atexit
import threading
import itertools
from functools import lru_cache
from concurrent.futures import ThreadPoolExecutor

NUM_THREADS = 1

counting_lock = threading.Lock()
uid2bytes_owned = {}
uid2paths_and_sizes = {}
total_inodes_counted = 0
done_counting = threading.Event()
total_inodes_used = None
total_bytes_used = 0


@lru_cache(maxsize=None)
def uid2username(uid: int) -> str:
    return pwd.getpwuid(uid).pw_name


def add_file_to_totals(path):
    global total_inodes_counted, uid2bytes_owned, uid2paths_and_sizes, total_bytes_used
    stat = os.stat(path)
    with counting_lock:
        uid2bytes_owned[stat.st_uid] = uid2bytes_owned.get(stat.st_uid, 0) + stat.st_size
        uid2paths_and_sizes.setdefault(stat.st_uid, []).append([path, stat.st_size])
        total_inodes_counted += 1
        total_bytes_used += stat.st_size


def human_readable_count(count: int) -> str:
    current_count = count
    current_unit = ""
    for new_unit in ["thousand", "million", "billion", "trillion", "quadrillion"]:
        new_count = current_count / 1000
        if new_count < 1:
            break
        else:
            current_count = new_count
            current_unit = new_unit
    if current_unit == "":
        return str(current_count)  # no decimals
    else:
        return f"{current_count:.2f} {current_unit}"


def human_readable_size(size_in_bytes: int) -> str:
    current_size = size_in_bytes
    current_unit = "bytes"
    for new_unit in ["KB", "MB", "GB", "TB", "PB"]:
        new_size = current_size / 1000
        if new_size < 1:
            break
        else:
            current_size = new_size
            current_unit = new_unit
    if current_unit == "bytes":
        return f"{current_size} bytes"  # no decimals
    else:
        return f"{current_size:.2f} {current_unit}"


def fmt_table(table: list[list]) -> list[str]:
    """
    I would use tabulate but I don't want nonstandard imports
    no table headers
    allows ANSI formatted elements
    """
    output_lines = []
    assert all(len(row) == len(table[0]) for row in table), "all rows must have the same length"
    column_widths = [0] * len(table[0])
    for row in table:
        for i, element in enumerate(row):
            if len(str(element)) > column_widths[i]:
                column_widths[i] = len(str(element))
    column_widths = [x + 1 for x in column_widths]  # add one space in between
    for row in table:
        line = ""
        for i, value in enumerate(row):
            padding_size = column_widths[i] - len(value)
            line += value + " " * padding_size
        output_lines.append(line)
    return output_lines


def print_current_totals():
    print(f"inodes counted: {human_readable_count(total_inodes_counted)}")
    if total_inodes_used is not None:
        progress_percent = (total_inodes_counted / total_inodes_used) * 100
        print(f"inode count progress: {progress_percent:.1f}%")
    if len(uid2bytes_owned) == 0:
        return
    sorted_uid2bytes_owned = {
        k: v for k, v in sorted(uid2bytes_owned.items(), key=lambda x: x[1], reverse=True)
    }
    usage_table = []
    for uid, bytes_owned in sorted_uid2bytes_owned.items():
        pcent = (bytes_owned / total_bytes_used) * 100
        usage_table.append([uid2username(uid), human_readable_size(bytes_owned), f"{pcent:.1f}%"])
    for line in fmt_table(usage_table):
        print(line)
    print()


def loop_print_current_totals(sleep_seconds=1):
    while not done_counting.is_set():
        print_current_totals()
        time.sleep(sleep_seconds)


def get_total_inodes_used_statvfs(path) -> int | None:
    """
    when statvfs produces different results for path and dirname(path),
    total file size in path is known.
    """
    cwd_statvfs = os.statvfs(path)
    parent_statvfs = os.statvfs(os.path.dirname(path))
    if cwd_statvfs == parent_statvfs:
        return None
    return cwd_statvfs.f_files - cwd_statvfs.f_ffree


# def enable_alternate_screen_mode():
#     print("\033[?1049h\033[H")


# def disable_alternate_screen_mode():
#     print("\033[?1049l")


# def sigint_handler(x, y):
#     disable_alternate_screen_mode()
#     sys.exit(1)


def main():
    global total_inodes_used
    # enable_alternate_screen_mode()
    # atexit.register(disable_alternate_screen_mode)
    # signal.signal(signal.SIGINT, sigint_handler)
    total_inodes_used = get_total_inodes_used_statvfs(os.path.realpath(os.getcwd()))
    if total_inodes_used == None:
        print(
            "this directory does not have a unique statvfs, so inode counting progress cannot be determined.",
            file=sys.stderr,
        )
    print_current_totals_thread = threading.Thread(target=loop_print_current_totals, daemon=True)
    print_current_totals_thread.start()
    with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
        walk_gen = os.walk(".")
        walk_path_gen = itertools.chain.from_iterable(
            (os.path.join(root, basename) for basename in files + dirs)
            for root, dirs, files in walk_gen
        )
        executor.map(add_file_to_totals, walk_path_gen)
    print_current_totals()
    sys.exit(0)
    # done_counting.set()
    # print_current_totals_thread.join()


if __name__ == "__main__":
    main()
