#!/bin/bash

print_usage_if_exists(){
    if [ -d "$1" ]; then
        /usr/bin/printf "$1: "
        df_out=$(/usr/bin/df -h "$1" --output='used,pcent,size' | /usr/bin/tail -n 1)
        pcent=$(echo "$df_out" | /usr/bin/awk '{print $2}' | /usr/bin/grep -oP '^\d+(?=%$)')
        if [ "$pcent" -gt "75" ]; then
            /usr/bin/printf '\033[0;31m' # red
            echo "$df_out" | /usr/bin/awk '{print $1" ("$2") of "$3}'
            /usr/bin/printf '\033[0m' # reset
        else
            echo "$df_out" | /usr/bin/awk '{print $1" ("$2") of "$3}'
        fi
    fi
}

# `groups` makes output delimited by spaces, find/replaces spaces for newlines, that's how grep likes it
my_pi_groups="$(/usr/bin/groups | /usr/bin/tr ' ' '\n' | /usr/bin/grep -e ^pi_)"

print_usage_if_exists ~
for group in $my_pi_groups; do
    print_usage_if_exists /work/$group
    print_usage_if_exists /project/$group
done
